/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_LINE_TARGET_COMMANDS_PB_H_INCLUDED
#define PB_QROMA_LINE_TARGET_COMMANDS_PB_H_INCLUDED
#include <pb.h>
#include "qroma-api4-ws2812fx.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ActivateLineTargetRequest { 
    bool has_backgroundColor;
    QromaColor backgroundColor; 
    bool has_targetColor;
    QromaColor targetColor; 
    uint32_t targetStartIndex; 
    uint32_t targetEndIndex; 
} ActivateLineTargetRequest;

typedef struct _QromaLineTargetCommand { 
    pb_size_t which_command;
    union {
        ActivateLineTargetRequest activateLineTarget;
    } command; 
} QromaLineTargetCommand;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ActivateLineTargetRequest_init_default   {false, QromaColor_init_default, false, QromaColor_init_default, 0, 0}
#define QromaLineTargetCommand_init_default      {0, {ActivateLineTargetRequest_init_default}}
#define ActivateLineTargetRequest_init_zero      {false, QromaColor_init_zero, false, QromaColor_init_zero, 0, 0}
#define QromaLineTargetCommand_init_zero         {0, {ActivateLineTargetRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define ActivateLineTargetRequest_backgroundColor_tag 1
#define ActivateLineTargetRequest_targetColor_tag 2
#define ActivateLineTargetRequest_targetStartIndex_tag 3
#define ActivateLineTargetRequest_targetEndIndex_tag 4
#define QromaLineTargetCommand_activateLineTarget_tag 1

/* Struct field encoding specification for nanopb */
#define ActivateLineTargetRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  backgroundColor,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  targetColor,       2) \
X(a, STATIC,   SINGULAR, UINT32,   targetStartIndex,   3) \
X(a, STATIC,   SINGULAR, UINT32,   targetEndIndex,    4)
#define ActivateLineTargetRequest_CALLBACK NULL
#define ActivateLineTargetRequest_DEFAULT NULL
#define ActivateLineTargetRequest_backgroundColor_MSGTYPE QromaColor
#define ActivateLineTargetRequest_targetColor_MSGTYPE QromaColor

#define QromaLineTargetCommand_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,activateLineTarget,command.activateLineTarget),   1)
#define QromaLineTargetCommand_CALLBACK NULL
#define QromaLineTargetCommand_DEFAULT NULL
#define QromaLineTargetCommand_command_activateLineTarget_MSGTYPE ActivateLineTargetRequest

extern const pb_msgdesc_t ActivateLineTargetRequest_msg;
extern const pb_msgdesc_t QromaLineTargetCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ActivateLineTargetRequest_fields &ActivateLineTargetRequest_msg
#define QromaLineTargetCommand_fields &QromaLineTargetCommand_msg

/* Maximum encoded size of messages (where known) */
#define ActivateLineTargetRequest_size           52
#define QromaLineTargetCommand_size              54

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
