# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: qroma-line-target-commands.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import qroma_api4_ws2812fx_pb2 as qroma__api4__ws2812fx__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='qroma-line-target-commands.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n qroma-line-target-commands.proto\x1a\x19qroma-api4-ws2812fx.proto\"\x95\x01\n\x19\x41\x63tivateLineTargetRequest\x12$\n\x0f\x62\x61\x63kgroundColor\x18\x01 \x01(\x0b\x32\x0b.QromaColor\x12 \n\x0btargetColor\x18\x02 \x01(\x0b\x32\x0b.QromaColor\x12\x18\n\x10targetStartIndex\x18\x03 \x01(\r\x12\x16\n\x0etargetEndIndex\x18\x04 \x01(\r\"]\n\x16QromaLineTargetCommand\x12\x38\n\x12\x61\x63tivateLineTarget\x18\x01 \x01(\x0b\x32\x1a.ActivateLineTargetRequestH\x00\x42\t\n\x07\x63ommandb\x06proto3'
  ,
  dependencies=[qroma__api4__ws2812fx__pb2.DESCRIPTOR,])




_ACTIVATELINETARGETREQUEST = _descriptor.Descriptor(
  name='ActivateLineTargetRequest',
  full_name='ActivateLineTargetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='backgroundColor', full_name='ActivateLineTargetRequest.backgroundColor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targetColor', full_name='ActivateLineTargetRequest.targetColor', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targetStartIndex', full_name='ActivateLineTargetRequest.targetStartIndex', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='targetEndIndex', full_name='ActivateLineTargetRequest.targetEndIndex', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=213,
)


_QROMALINETARGETCOMMAND = _descriptor.Descriptor(
  name='QromaLineTargetCommand',
  full_name='QromaLineTargetCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activateLineTarget', full_name='QromaLineTargetCommand.activateLineTarget', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='QromaLineTargetCommand.command',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=215,
  serialized_end=308,
)

_ACTIVATELINETARGETREQUEST.fields_by_name['backgroundColor'].message_type = qroma__api4__ws2812fx__pb2._QROMACOLOR
_ACTIVATELINETARGETREQUEST.fields_by_name['targetColor'].message_type = qroma__api4__ws2812fx__pb2._QROMACOLOR
_QROMALINETARGETCOMMAND.fields_by_name['activateLineTarget'].message_type = _ACTIVATELINETARGETREQUEST
_QROMALINETARGETCOMMAND.oneofs_by_name['command'].fields.append(
  _QROMALINETARGETCOMMAND.fields_by_name['activateLineTarget'])
_QROMALINETARGETCOMMAND.fields_by_name['activateLineTarget'].containing_oneof = _QROMALINETARGETCOMMAND.oneofs_by_name['command']
DESCRIPTOR.message_types_by_name['ActivateLineTargetRequest'] = _ACTIVATELINETARGETREQUEST
DESCRIPTOR.message_types_by_name['QromaLineTargetCommand'] = _QROMALINETARGETCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActivateLineTargetRequest = _reflection.GeneratedProtocolMessageType('ActivateLineTargetRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATELINETARGETREQUEST,
  '__module__' : 'qroma_line_target_commands_pb2'
  # @@protoc_insertion_point(class_scope:ActivateLineTargetRequest)
  })
_sym_db.RegisterMessage(ActivateLineTargetRequest)

QromaLineTargetCommand = _reflection.GeneratedProtocolMessageType('QromaLineTargetCommand', (_message.Message,), {
  'DESCRIPTOR' : _QROMALINETARGETCOMMAND,
  '__module__' : 'qroma_line_target_commands_pb2'
  # @@protoc_insertion_point(class_scope:QromaLineTargetCommand)
  })
_sym_db.RegisterMessage(QromaLineTargetCommand)


# @@protoc_insertion_point(module_scope)
