/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "qroma-api4-ws2812fx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(WS2812FxConstructAndInitRequest, WS2812FxConstructAndInitRequest, AUTO)


PB_BIND(NoArgRequest, NoArgRequest, AUTO)


PB_BIND(NoArgResponse, NoArgResponse, AUTO)


PB_BIND(QromaColor, QromaColor, AUTO)


PB_BIND(SetPixelColorRequest, SetPixelColorRequest, AUTO)


PB_BIND(FillRequest, FillRequest, AUTO)


PB_BIND(SetModeRequest, SetModeRequest, AUTO)


PB_BIND(SetBrightnessRequest, SetBrightnessRequest, AUTO)


PB_BIND(SetSpeedRequest, SetSpeedRequest, AUTO)


PB_BIND(IncreaseBrightnessRequest, IncreaseBrightnessRequest, AUTO)


PB_BIND(DecreaseBrightnessRequest, DecreaseBrightnessRequest, AUTO)


PB_BIND(Ws2812FxApiTx, Ws2812FxApiTx, AUTO)


PB_BIND(Ws2812FxApiRx, Ws2812FxApiRx, AUTO)







