/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_QROMA_API4_WS2812FX_PB_H_INCLUDED
#define PB_QROMA_API4_WS2812FX_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* WS2812FX modes - maps to the FX_MODE_* constants */
typedef enum _WS2812FXMode { 
    WS2812FXMode_WS2812FX_MODE_STATIC = 0, 
    WS2812FXMode_WS2812FX_MODE_BLINK = 1, 
    WS2812FXMode_WS2812FX_MODE_BREATH = 2, 
    WS2812FXMode_WS2812FX_MODE_COLOR_WIPE = 3, 
    WS2812FXMode_WS2812FX_MODE_COLOR_WIPE_INV = 4, 
    WS2812FXMode_WS2812FX_MODE_COLOR_WIPE_REV = 5, 
    WS2812FXMode_WS2812FX_MODE_COLOR_WIPE_REV_INV = 6, 
    WS2812FXMode_WS2812FX_MODE_COLOR_WIPE_RANDOM = 7, 
    WS2812FXMode_WS2812FX_MODE_RANDOM_COLOR = 8, 
    WS2812FXMode_WS2812FX_MODE_SINGLE_DYNAMIC = 9, 
    WS2812FXMode_WS2812FX_MODE_MULTI_DYNAMIC = 10, 
    WS2812FXMode_WS2812FX_MODE_RAINBOW = 11, 
    WS2812FXMode_WS2812FX_MODE_RAINBOW_CYCLE = 12, 
    WS2812FXMode_WS2812FX_MODE_SCAN = 13, 
    WS2812FXMode_WS2812FX_MODE_DUAL_SCAN = 14, 
    WS2812FXMode_WS2812FX_MODE_FADE = 15, 
    WS2812FXMode_WS2812FX_MODE_THEATER_CHASE = 16, 
    WS2812FXMode_WS2812FX_MODE_THEATER_CHASE_RAINBOW = 17, 
    WS2812FXMode_WS2812FX_MODE_RUNNING_LIGHTS = 18, 
    WS2812FXMode_WS2812FX_MODE_TWINKLE = 19, 
    WS2812FXMode_WS2812FX_MODE_TWINKLE_FADE = 20, 
    WS2812FXMode_WS2812FX_MODE_TWINKLE_RANDOM = 21, 
    WS2812FXMode_WS2812FX_MODE_SPARKLE = 22, 
    WS2812FXMode_WS2812FX_MODE_FLASH_SPARKLE = 23, 
    WS2812FXMode_WS2812FX_MODE_HYPER_SPARKLE = 24, 
    WS2812FXMode_WS2812FX_MODE_STROBE = 25, 
    WS2812FXMode_WS2812FX_MODE_STROBE_RAINBOW = 26, 
    WS2812FXMode_WS2812FX_MODE_MULTI_STROBE = 27, 
    WS2812FXMode_WS2812FX_MODE_BLINK_RAINBOW = 28, 
    WS2812FXMode_WS2812FX_MODE_CHASE_WHITE = 29, 
    WS2812FXMode_WS2812FX_MODE_CHASE_COLOR = 30, 
    WS2812FXMode_WS2812FX_MODE_CHASE_RANDOM = 31, 
    WS2812FXMode_WS2812FX_MODE_CHASE_RAINBOW = 32, 
    WS2812FXMode_WS2812FX_MODE_CHASE_FLASH = 33, 
    WS2812FXMode_WS2812FX_MODE_CHASE_FLASH_RANDOM = 34, 
    WS2812FXMode_WS2812FX_MODE_CHASE_RAINBOW_WHITE = 35, 
    WS2812FXMode_WS2812FX_MODE_CHASE_BLACKOUT = 36, 
    WS2812FXMode_WS2812FX_MODE_CHASE_BLACKOUT_RAINBOW = 37, 
    WS2812FXMode_WS2812FX_MODE_COLOR_SWEEP_RANDOM = 38, 
    WS2812FXMode_WS2812FX_MODE_RUNNING_COLOR = 39, 
    WS2812FXMode_WS2812FX_MODE_RUNNING_RED_BLUE = 40, 
    WS2812FXMode_WS2812FX_MODE_RUNNING_RANDOM = 41, 
    WS2812FXMode_WS2812FX_MODE_LARSON_SCANNER = 42, 
    WS2812FXMode_WS2812FX_MODE_COMET = 43, 
    WS2812FXMode_WS2812FX_MODE_FIREWORKS = 44, 
    WS2812FXMode_WS2812FX_MODE_FIREWORKS_RANDOM = 45, 
    WS2812FXMode_WS2812FX_MODE_MERRY_CHRISTMAS = 46, 
    WS2812FXMode_WS2812FX_MODE_FIRE_FLICKER = 47, 
    WS2812FXMode_WS2812FX_MODE_FIRE_FLICKER_SOFT = 48, 
    WS2812FXMode_WS2812FX_MODE_FIRE_FLICKER_INTENSE = 49, 
    WS2812FXMode_WS2812FX_MODE_CIRCUS_COMBUSTUS = 50, 
    WS2812FXMode_WS2812FX_MODE_HALLOWEEN = 51, 
    WS2812FXMode_WS2812FX_MODE_BICOLOR_CHASE = 52, 
    WS2812FXMode_WS2812FX_MODE_TRICOLOR_CHASE = 53, 
    WS2812FXMode_WS2812FX_MODE_ICU = 54, 
    WS2812FXMode_WS2812FX_MODE_CUSTOM_0 = 55, 
    WS2812FXMode_WS2812FX_MODE_CUSTOM_1 = 56, 
    WS2812FXMode_WS2812FX_MODE_CUSTOM_2 = 57, 
    WS2812FXMode_WS2812FX_MODE_CUSTOM_3 = 58 
} WS2812FXMode;

/* WS2812FX segment modes */
typedef enum _WS2812FXSegmentMode { 
    WS2812FXSegmentMode_WS2812FX_SEGMENT_MODE_FREEZE = 0, 
    WS2812FXSegmentMode_WS2812FX_SEGMENT_MODE_HOLD = 1, 
    WS2812FXSegmentMode_WS2812FX_SEGMENT_MODE_OFF = 2, 
    WS2812FXSegmentMode_WS2812FX_SEGMENT_MODE_ON = 3 
} WS2812FXSegmentMode;

/* WS2812FX color orders */
typedef enum _WS2812FXColorOrder { 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_NOT_SET = 0, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_RGB = 1, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_RBG = 2, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_GRB = 3, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_GBR = 4, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BRG = 5, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BGR = 6, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_WRGB = 7, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_WRBG = 8, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_WGRB = 9, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_WGBR = 10, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_WBRG = 11, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_WBGR = 12, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_RWGB = 13, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_RWBG = 14, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_RGWB = 15, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_RGBW = 16, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_RBWG = 17, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_RBGW = 18, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_GWRB = 19, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_GWBR = 20, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_GRWB = 21, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_GRBW = 22, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_GBWR = 23, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_GBRW = 24, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BWRG = 25, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BWGR = 26, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BRWG = 27, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BRGW = 28, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BGWR = 29, 
    WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BGRW = 30 
} WS2812FXColorOrder;

typedef enum _WS2812FX_NeoPixelTxRate { 
    WS2812FX_NeoPixelTxRate_WS2812FX_NEO_PIXEL_TX_RATE_NOT_SET = 0, 
    WS2812FX_NeoPixelTxRate_WS2812FX_NEO_PIXEL_TX_RATE_400_KHZ = 1, 
    WS2812FX_NeoPixelTxRate_WS2812FX_NEO_PIXEL_TX_RATE_800_KHZ = 2 
} WS2812FX_NeoPixelTxRate;

/* Struct definitions */
typedef struct _NoArgRequest { 
    char dummy_field;
} NoArgRequest;

typedef struct _NoArgResponse { 
    char dummy_field;
} NoArgResponse;

typedef struct _DecreaseBrightnessRequest { 
    uint32_t amount; 
} DecreaseBrightnessRequest;

typedef struct _IncreaseBrightnessRequest { 
    uint32_t amount; 
} IncreaseBrightnessRequest;

typedef struct _QromaColor { 
    uint32_t red; 
    uint32_t green; 
    uint32_t blue; 
} QromaColor;

typedef struct _SetBrightnessRequest { 
    uint32_t brightness; 
} SetBrightnessRequest;

typedef struct _SetModeRequest { 
    WS2812FXMode mode; 
} SetModeRequest;

typedef struct _SetSpeedRequest { 
    uint32_t speed; 
} SetSpeedRequest;

/* Initialize WS2812FX strip */
typedef struct _WS2812FxConstructAndInitRequest { 
    uint32_t ledCount; /* Number of LEDs in strip */
    uint32_t pin; /* GPIO pin number */
    WS2812FXColorOrder neoPixelRgbOrder; /* Color order */
    WS2812FX_NeoPixelTxRate neoPixelTxRate; /* NeoPixel transmission rate */
} WS2812FxConstructAndInitRequest;

typedef struct _FillRequest { 
    bool has_color;
    QromaColor color; 
    uint32_t firstPixel; 
    uint32_t numPixels; 
} FillRequest;

typedef struct _SetPixelColorRequest { 
    uint32_t pixelIndex; 
    bool has_color;
    QromaColor color; 
} SetPixelColorRequest;

/* Main response wrapper */
typedef struct _Ws2812FxApiRx { 
    pb_size_t which_response;
    union {
        WS2812FxConstructAndInitRequest ackConstructAndInit;
        NoArgResponse ackStart;
        NoArgResponse ackStop;
        NoArgResponse ackPause;
        NoArgResponse ackResume;
        NoArgResponse ackService;
        NoArgResponse ackShow;
        NoArgResponse ackStripOff;
        NoArgResponse ackFadeOut;
        QromaColor ackFadeOutToColor;
        SetModeRequest ackSetMode;
        QromaColor ackSetColor;
        SetSpeedRequest ackSetSpeed;
        FillRequest ackFill;
        SetPixelColorRequest ackSetPixelColor;
        SetBrightnessRequest ackSetBrightness;
        IncreaseBrightnessRequest ackIncreaseBrightness;
        DecreaseBrightnessRequest ackDecreaseBrightness;
    } response; 
} Ws2812FxApiRx;

/* Main command wrapper */
typedef struct _Ws2812FxApiTx { 
    pb_size_t which_request;
    union {
        WS2812FxConstructAndInitRequest constructAndInit;
        NoArgRequest start;
        NoArgRequest stop;
        NoArgRequest pause;
        NoArgRequest resume;
        NoArgRequest service;
        NoArgRequest show;
        NoArgRequest stripOff;
        NoArgRequest fadeOut;
        QromaColor fadeOutToColor;
        SetModeRequest setMode;
        QromaColor setColor;
        SetSpeedRequest setSpeed;
        FillRequest fill;
        SetPixelColorRequest setPixelColor;
        SetBrightnessRequest setBrightness;
        IncreaseBrightnessRequest increaseBrightness;
        DecreaseBrightnessRequest decreaseBrightness;
    } request; 
} Ws2812FxApiTx;


/* Helper constants for enums */
#define _WS2812FXMode_MIN WS2812FXMode_WS2812FX_MODE_STATIC
#define _WS2812FXMode_MAX WS2812FXMode_WS2812FX_MODE_CUSTOM_3
#define _WS2812FXMode_ARRAYSIZE ((WS2812FXMode)(WS2812FXMode_WS2812FX_MODE_CUSTOM_3+1))

#define _WS2812FXSegmentMode_MIN WS2812FXSegmentMode_WS2812FX_SEGMENT_MODE_FREEZE
#define _WS2812FXSegmentMode_MAX WS2812FXSegmentMode_WS2812FX_SEGMENT_MODE_ON
#define _WS2812FXSegmentMode_ARRAYSIZE ((WS2812FXSegmentMode)(WS2812FXSegmentMode_WS2812FX_SEGMENT_MODE_ON+1))

#define _WS2812FXColorOrder_MIN WS2812FXColorOrder_WS2812FX_COLOR_ORDER_NOT_SET
#define _WS2812FXColorOrder_MAX WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BGRW
#define _WS2812FXColorOrder_ARRAYSIZE ((WS2812FXColorOrder)(WS2812FXColorOrder_WS2812FX_COLOR_ORDER_BGRW+1))

#define _WS2812FX_NeoPixelTxRate_MIN WS2812FX_NeoPixelTxRate_WS2812FX_NEO_PIXEL_TX_RATE_NOT_SET
#define _WS2812FX_NeoPixelTxRate_MAX WS2812FX_NeoPixelTxRate_WS2812FX_NEO_PIXEL_TX_RATE_800_KHZ
#define _WS2812FX_NeoPixelTxRate_ARRAYSIZE ((WS2812FX_NeoPixelTxRate)(WS2812FX_NeoPixelTxRate_WS2812FX_NEO_PIXEL_TX_RATE_800_KHZ+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define WS2812FxConstructAndInitRequest_init_default {0, 0, _WS2812FXColorOrder_MIN, _WS2812FX_NeoPixelTxRate_MIN}
#define NoArgRequest_init_default                {0}
#define NoArgResponse_init_default               {0}
#define QromaColor_init_default                  {0, 0, 0}
#define SetPixelColorRequest_init_default        {0, false, QromaColor_init_default}
#define FillRequest_init_default                 {false, QromaColor_init_default, 0, 0}
#define SetModeRequest_init_default              {_WS2812FXMode_MIN}
#define SetBrightnessRequest_init_default        {0}
#define SetSpeedRequest_init_default             {0}
#define IncreaseBrightnessRequest_init_default   {0}
#define DecreaseBrightnessRequest_init_default   {0}
#define Ws2812FxApiTx_init_default               {0, {WS2812FxConstructAndInitRequest_init_default}}
#define Ws2812FxApiRx_init_default               {0, {WS2812FxConstructAndInitRequest_init_default}}
#define WS2812FxConstructAndInitRequest_init_zero {0, 0, _WS2812FXColorOrder_MIN, _WS2812FX_NeoPixelTxRate_MIN}
#define NoArgRequest_init_zero                   {0}
#define NoArgResponse_init_zero                  {0}
#define QromaColor_init_zero                     {0, 0, 0}
#define SetPixelColorRequest_init_zero           {0, false, QromaColor_init_zero}
#define FillRequest_init_zero                    {false, QromaColor_init_zero, 0, 0}
#define SetModeRequest_init_zero                 {_WS2812FXMode_MIN}
#define SetBrightnessRequest_init_zero           {0}
#define SetSpeedRequest_init_zero                {0}
#define IncreaseBrightnessRequest_init_zero      {0}
#define DecreaseBrightnessRequest_init_zero      {0}
#define Ws2812FxApiTx_init_zero                  {0, {WS2812FxConstructAndInitRequest_init_zero}}
#define Ws2812FxApiRx_init_zero                  {0, {WS2812FxConstructAndInitRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define DecreaseBrightnessRequest_amount_tag     1
#define IncreaseBrightnessRequest_amount_tag     1
#define QromaColor_red_tag                       1
#define QromaColor_green_tag                     2
#define QromaColor_blue_tag                      3
#define SetBrightnessRequest_brightness_tag      1
#define SetModeRequest_mode_tag                  1
#define SetSpeedRequest_speed_tag                1
#define WS2812FxConstructAndInitRequest_ledCount_tag 1
#define WS2812FxConstructAndInitRequest_pin_tag  2
#define WS2812FxConstructAndInitRequest_neoPixelRgbOrder_tag 3
#define WS2812FxConstructAndInitRequest_neoPixelTxRate_tag 4
#define FillRequest_color_tag                    1
#define FillRequest_firstPixel_tag               2
#define FillRequest_numPixels_tag                3
#define SetPixelColorRequest_pixelIndex_tag      1
#define SetPixelColorRequest_color_tag           2
#define Ws2812FxApiRx_ackConstructAndInit_tag    1
#define Ws2812FxApiRx_ackStart_tag               2
#define Ws2812FxApiRx_ackStop_tag                3
#define Ws2812FxApiRx_ackPause_tag               4
#define Ws2812FxApiRx_ackResume_tag              5
#define Ws2812FxApiRx_ackService_tag             6
#define Ws2812FxApiRx_ackShow_tag                7
#define Ws2812FxApiRx_ackStripOff_tag            8
#define Ws2812FxApiRx_ackFadeOut_tag             9
#define Ws2812FxApiRx_ackFadeOutToColor_tag      10
#define Ws2812FxApiRx_ackSetMode_tag             11
#define Ws2812FxApiRx_ackSetColor_tag            12
#define Ws2812FxApiRx_ackSetSpeed_tag            13
#define Ws2812FxApiRx_ackFill_tag                14
#define Ws2812FxApiRx_ackSetPixelColor_tag       15
#define Ws2812FxApiRx_ackSetBrightness_tag       16
#define Ws2812FxApiRx_ackIncreaseBrightness_tag  17
#define Ws2812FxApiRx_ackDecreaseBrightness_tag  18
#define Ws2812FxApiTx_constructAndInit_tag       1
#define Ws2812FxApiTx_start_tag                  2
#define Ws2812FxApiTx_stop_tag                   3
#define Ws2812FxApiTx_pause_tag                  4
#define Ws2812FxApiTx_resume_tag                 5
#define Ws2812FxApiTx_service_tag                6
#define Ws2812FxApiTx_show_tag                   7
#define Ws2812FxApiTx_stripOff_tag               8
#define Ws2812FxApiTx_fadeOut_tag                9
#define Ws2812FxApiTx_fadeOutToColor_tag         10
#define Ws2812FxApiTx_setMode_tag                11
#define Ws2812FxApiTx_setColor_tag               12
#define Ws2812FxApiTx_setSpeed_tag               13
#define Ws2812FxApiTx_fill_tag                   14
#define Ws2812FxApiTx_setPixelColor_tag          15
#define Ws2812FxApiTx_setBrightness_tag          16
#define Ws2812FxApiTx_increaseBrightness_tag     17
#define Ws2812FxApiTx_decreaseBrightness_tag     18

/* Struct field encoding specification for nanopb */
#define WS2812FxConstructAndInitRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ledCount,          1) \
X(a, STATIC,   SINGULAR, UINT32,   pin,               2) \
X(a, STATIC,   SINGULAR, UENUM,    neoPixelRgbOrder,   3) \
X(a, STATIC,   SINGULAR, UENUM,    neoPixelTxRate,    4)
#define WS2812FxConstructAndInitRequest_CALLBACK NULL
#define WS2812FxConstructAndInitRequest_DEFAULT NULL

#define NoArgRequest_FIELDLIST(X, a) \

#define NoArgRequest_CALLBACK NULL
#define NoArgRequest_DEFAULT NULL

#define NoArgResponse_FIELDLIST(X, a) \

#define NoArgResponse_CALLBACK NULL
#define NoArgResponse_DEFAULT NULL

#define QromaColor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   red,               1) \
X(a, STATIC,   SINGULAR, UINT32,   green,             2) \
X(a, STATIC,   SINGULAR, UINT32,   blue,              3)
#define QromaColor_CALLBACK NULL
#define QromaColor_DEFAULT NULL

#define SetPixelColorRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pixelIndex,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color,             2)
#define SetPixelColorRequest_CALLBACK NULL
#define SetPixelColorRequest_DEFAULT NULL
#define SetPixelColorRequest_color_MSGTYPE QromaColor

#define FillRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  color,             1) \
X(a, STATIC,   SINGULAR, UINT32,   firstPixel,        2) \
X(a, STATIC,   SINGULAR, UINT32,   numPixels,         3)
#define FillRequest_CALLBACK NULL
#define FillRequest_DEFAULT NULL
#define FillRequest_color_MSGTYPE QromaColor

#define SetModeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1)
#define SetModeRequest_CALLBACK NULL
#define SetModeRequest_DEFAULT NULL

#define SetBrightnessRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   brightness,        1)
#define SetBrightnessRequest_CALLBACK NULL
#define SetBrightnessRequest_DEFAULT NULL

#define SetSpeedRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   speed,             1)
#define SetSpeedRequest_CALLBACK NULL
#define SetSpeedRequest_DEFAULT NULL

#define IncreaseBrightnessRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   amount,            1)
#define IncreaseBrightnessRequest_CALLBACK NULL
#define IncreaseBrightnessRequest_DEFAULT NULL

#define DecreaseBrightnessRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   amount,            1)
#define DecreaseBrightnessRequest_CALLBACK NULL
#define DecreaseBrightnessRequest_DEFAULT NULL

#define Ws2812FxApiTx_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,constructAndInit,request.constructAndInit),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,start,request.start),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,stop,request.stop),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,pause,request.pause),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,resume,request.resume),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,service,request.service),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,show,request.show),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,stripOff,request.stripOff),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,fadeOut,request.fadeOut),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,fadeOutToColor,request.fadeOutToColor),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,setMode,request.setMode),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,setColor,request.setColor),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,setSpeed,request.setSpeed),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,fill,request.fill),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,setPixelColor,request.setPixelColor),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,setBrightness,request.setBrightness),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,increaseBrightness,request.increaseBrightness),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (request,decreaseBrightness,request.decreaseBrightness),  18)
#define Ws2812FxApiTx_CALLBACK NULL
#define Ws2812FxApiTx_DEFAULT NULL
#define Ws2812FxApiTx_request_constructAndInit_MSGTYPE WS2812FxConstructAndInitRequest
#define Ws2812FxApiTx_request_start_MSGTYPE NoArgRequest
#define Ws2812FxApiTx_request_stop_MSGTYPE NoArgRequest
#define Ws2812FxApiTx_request_pause_MSGTYPE NoArgRequest
#define Ws2812FxApiTx_request_resume_MSGTYPE NoArgRequest
#define Ws2812FxApiTx_request_service_MSGTYPE NoArgRequest
#define Ws2812FxApiTx_request_show_MSGTYPE NoArgRequest
#define Ws2812FxApiTx_request_stripOff_MSGTYPE NoArgRequest
#define Ws2812FxApiTx_request_fadeOut_MSGTYPE NoArgRequest
#define Ws2812FxApiTx_request_fadeOutToColor_MSGTYPE QromaColor
#define Ws2812FxApiTx_request_setMode_MSGTYPE SetModeRequest
#define Ws2812FxApiTx_request_setColor_MSGTYPE QromaColor
#define Ws2812FxApiTx_request_setSpeed_MSGTYPE SetSpeedRequest
#define Ws2812FxApiTx_request_fill_MSGTYPE FillRequest
#define Ws2812FxApiTx_request_setPixelColor_MSGTYPE SetPixelColorRequest
#define Ws2812FxApiTx_request_setBrightness_MSGTYPE SetBrightnessRequest
#define Ws2812FxApiTx_request_increaseBrightness_MSGTYPE IncreaseBrightnessRequest
#define Ws2812FxApiTx_request_decreaseBrightness_MSGTYPE DecreaseBrightnessRequest

#define Ws2812FxApiRx_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackConstructAndInit,response.ackConstructAndInit),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackStart,response.ackStart),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackStop,response.ackStop),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackPause,response.ackPause),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackResume,response.ackResume),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackService,response.ackService),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackShow,response.ackShow),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackStripOff,response.ackStripOff),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackFadeOut,response.ackFadeOut),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackFadeOutToColor,response.ackFadeOutToColor),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackSetMode,response.ackSetMode),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackSetColor,response.ackSetColor),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackSetSpeed,response.ackSetSpeed),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackFill,response.ackFill),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackSetPixelColor,response.ackSetPixelColor),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackSetBrightness,response.ackSetBrightness),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackIncreaseBrightness,response.ackIncreaseBrightness),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ackDecreaseBrightness,response.ackDecreaseBrightness),  18)
#define Ws2812FxApiRx_CALLBACK NULL
#define Ws2812FxApiRx_DEFAULT NULL
#define Ws2812FxApiRx_response_ackConstructAndInit_MSGTYPE WS2812FxConstructAndInitRequest
#define Ws2812FxApiRx_response_ackStart_MSGTYPE NoArgResponse
#define Ws2812FxApiRx_response_ackStop_MSGTYPE NoArgResponse
#define Ws2812FxApiRx_response_ackPause_MSGTYPE NoArgResponse
#define Ws2812FxApiRx_response_ackResume_MSGTYPE NoArgResponse
#define Ws2812FxApiRx_response_ackService_MSGTYPE NoArgResponse
#define Ws2812FxApiRx_response_ackShow_MSGTYPE NoArgResponse
#define Ws2812FxApiRx_response_ackStripOff_MSGTYPE NoArgResponse
#define Ws2812FxApiRx_response_ackFadeOut_MSGTYPE NoArgResponse
#define Ws2812FxApiRx_response_ackFadeOutToColor_MSGTYPE QromaColor
#define Ws2812FxApiRx_response_ackSetMode_MSGTYPE SetModeRequest
#define Ws2812FxApiRx_response_ackSetColor_MSGTYPE QromaColor
#define Ws2812FxApiRx_response_ackSetSpeed_MSGTYPE SetSpeedRequest
#define Ws2812FxApiRx_response_ackFill_MSGTYPE FillRequest
#define Ws2812FxApiRx_response_ackSetPixelColor_MSGTYPE SetPixelColorRequest
#define Ws2812FxApiRx_response_ackSetBrightness_MSGTYPE SetBrightnessRequest
#define Ws2812FxApiRx_response_ackIncreaseBrightness_MSGTYPE IncreaseBrightnessRequest
#define Ws2812FxApiRx_response_ackDecreaseBrightness_MSGTYPE DecreaseBrightnessRequest

extern const pb_msgdesc_t WS2812FxConstructAndInitRequest_msg;
extern const pb_msgdesc_t NoArgRequest_msg;
extern const pb_msgdesc_t NoArgResponse_msg;
extern const pb_msgdesc_t QromaColor_msg;
extern const pb_msgdesc_t SetPixelColorRequest_msg;
extern const pb_msgdesc_t FillRequest_msg;
extern const pb_msgdesc_t SetModeRequest_msg;
extern const pb_msgdesc_t SetBrightnessRequest_msg;
extern const pb_msgdesc_t SetSpeedRequest_msg;
extern const pb_msgdesc_t IncreaseBrightnessRequest_msg;
extern const pb_msgdesc_t DecreaseBrightnessRequest_msg;
extern const pb_msgdesc_t Ws2812FxApiTx_msg;
extern const pb_msgdesc_t Ws2812FxApiRx_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define WS2812FxConstructAndInitRequest_fields &WS2812FxConstructAndInitRequest_msg
#define NoArgRequest_fields &NoArgRequest_msg
#define NoArgResponse_fields &NoArgResponse_msg
#define QromaColor_fields &QromaColor_msg
#define SetPixelColorRequest_fields &SetPixelColorRequest_msg
#define FillRequest_fields &FillRequest_msg
#define SetModeRequest_fields &SetModeRequest_msg
#define SetBrightnessRequest_fields &SetBrightnessRequest_msg
#define SetSpeedRequest_fields &SetSpeedRequest_msg
#define IncreaseBrightnessRequest_fields &IncreaseBrightnessRequest_msg
#define DecreaseBrightnessRequest_fields &DecreaseBrightnessRequest_msg
#define Ws2812FxApiTx_fields &Ws2812FxApiTx_msg
#define Ws2812FxApiRx_fields &Ws2812FxApiRx_msg

/* Maximum encoded size of messages (where known) */
#define DecreaseBrightnessRequest_size           6
#define FillRequest_size                         32
#define IncreaseBrightnessRequest_size           6
#define NoArgRequest_size                        0
#define NoArgResponse_size                       0
#define QromaColor_size                          18
#define SetBrightnessRequest_size                6
#define SetModeRequest_size                      2
#define SetPixelColorRequest_size                26
#define SetSpeedRequest_size                     6
#define WS2812FxConstructAndInitRequest_size     16
#define Ws2812FxApiRx_size                       34
#define Ws2812FxApiTx_size                       34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
